collections:
- name: ansible.netcommon
  version: 8.1.0
- name: ansible.posix
  version: 2.1.0
- name: ansible.utils
  version: 6.0.0
- name: community.crypto
  version: 3.0.5
- name: community.general
  version: 12.0.0
- name: fedora.linux_system_roles
  version: 1.110.1
- name: freeipa.ansible_freeipa
  version: 1.15.1
- name: microsoft.sql
  version: 2.6.4
- name: sap.linux
  version: 3.1.4
