collections:
- name: fedora.linux_system_roles
  version: 1.22.0
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.1.0
- name: freeipa.ansible_freeipa
  version: 1.7.0
- name: ansible.netcommon
  version: 3.0.0
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 2.3.0
- name: community.general
  version: 4.8.0
