collections:
- name: fedora.linux_system_roles
  version: 1.30.4
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.2.4
- name: freeipa.ansible_freeipa
  version: 1.8.4
- name: ansible.netcommon
  version: 4.1.0
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.8.1
- name: community.general
  version: 6.0.1
