collections:
- name: fedora.linux_system_roles
  version: 1.24.2
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.1.1
- name: freeipa.ansible_freeipa
  version: 1.8.1
- name: ansible.netcommon
  version: 3.0.1
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.4.0
- name: community.general
  version: 5.2.0
