collections:
- name: fedora.linux_system_roles
  version: 1.33.1
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.2.4
- name: freeipa.ansible_freeipa
  version: 1.9.0
- name: ansible.netcommon
  version: 4.1.0
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.10.0
- name: community.general
  version: 6.1.0
