collections:
- name: ansible.netcommon
  version: 8.4.0
- name: ansible.posix
  version: 2.1.0
- name: ansible.utils
  version: 6.0.1
- name: community.crypto
  version: 3.1.0
- name: community.general
  version: 12.3.0
- name: fedora.linux_system_roles
  version: 1.120.0
- name: freeipa.ansible_freeipa
  version: 1.16.0
- name: microsoft.sql
  version: 2.6.6
- name: sap.linux
  version: 3.1.4
