collections:
- name: ansible.netcommon
  version: 6.0.0
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 3.1.0
- name: community.crypto
  version: 2.18.0
- name: community.general
  version: 8.4.0
- name: fedora.linux_system_roles
  version: 1.75.2
- name: freeipa.ansible_freeipa
  version: 1.12.1
- name: microsoft.sql
  version: 2.2.2
- name: sap.linux
  version: 3.1.4
