collections:
- name: ansible.netcommon
  version: 7.1.0
- name: ansible.posix
  version: 2.0.0
- name: ansible.utils
  version: 5.1.2
- name: community.crypto
  version: 2.25.0
- name: community.general
  version: 10.4.0
- name: fedora.linux_system_roles
  version: 1.95.5
- name: freeipa.ansible_freeipa
  version: 1.14.5
- name: microsoft.sql
  version: 2.5.2
- name: sap.linux
  version: 3.1.4
