collections:
- name: fedora.linux_system_roles
  version: 1.18.0
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.1.0
- name: freeipa.ansible_freeipa
  version: 1.6.2
- name: ansible.netcommon
  version: 2.6.1
- name: ansible.posix
  version: 1.3.0
- name: community.crypto
  version: 2.2.4
- name: community.general
  version: 4.6.1
