collections:
- name: ansible.netcommon
  version: 7.1.0
- name: ansible.posix
  version: 1.6.2
- name: ansible.utils
  version: 5.1.2
- name: community.crypto
  version: 2.22.3
- name: community.general
  version: 10.0.1
- name: fedora.linux_system_roles
  version: 1.90.3
- name: freeipa.ansible_freeipa
  version: 1.14.0
- name: microsoft.sql
  version: 2.5.0
- name: sap.linux
  version: 3.1.4
