collections:
- name: ansible.netcommon
  version: 8.0.0
- name: ansible.posix
  version: 2.0.0
- name: ansible.utils
  version: 6.0.0
- name: community.crypto
  version: 2.26.3
- name: community.general
  version: 11.0.0
- name: fedora.linux_system_roles
  version: 1.104.0
- name: freeipa.ansible_freeipa
  version: 1.14.7
- name: microsoft.sql
  version: 2.5.2
- name: sap.linux
  version: 3.1.4
