collections:
- name: ansible.netcommon
  version: 6.0.0
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 3.1.0
- name: community.crypto
  version: 2.17.1
- name: community.general
  version: 8.3.0
- name: fedora.linux_system_roles
  version: 1.71.1
- name: freeipa.ansible_freeipa
  version: 1.12.0
- name: microsoft.sql
  version: 2.2.1
- name: sap.linux
  version: 3.1.4
