collections:
- name: fedora.linux_system_roles
  version: 1.27.0
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.2.4
- name: freeipa.ansible_freeipa
  version: 1.8.4
- name: ansible.netcommon
  version: 3.1.2
- name: ansible.posix
  version: 1.4.0
- name: community.crypto
  version: 2.7.0
- name: community.general
  version: 5.6.0
