collections:
- name: ansible.netcommon
  version: 8.0.1
- name: ansible.posix
  version: 2.1.0
- name: ansible.utils
  version: 6.0.0
- name: community.crypto
  version: 3.0.0
- name: community.general
  version: 11.1.0
- name: fedora.linux_system_roles
  version: 1.106.1
- name: freeipa.ansible_freeipa
  version: 1.14.7
- name: microsoft.sql
  version: 2.6.2
- name: sap.linux
  version: 3.1.4
