collections:
- name: fedora.linux_system_roles
  version: 1.35.0
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.3.0
- name: freeipa.ansible_freeipa
  version: 1.9.2
- name: ansible.netcommon
  version: 4.1.0
- name: ansible.posix
  version: 1.5.1
- name: community.crypto
  version: 2.10.0
- name: community.general
  version: 6.3.0
