collections:
- name: fedora.linux_system_roles
  version: 1.38.3
- name: sap.linux
  version: 3.1.4
- name: microsoft.sql
  version: 1.3.1
- name: freeipa.ansible_freeipa
  version: 1.10.0
- name: ansible.netcommon
  version: 5.1.1
- name: ansible.posix
  version: 1.5.4
- name: community.crypto
  version: 2.13.1
- name: community.general
  version: 7.0.1
