collections:
- name: ansible.netcommon
  version: 6.1.3
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 4.1.0
- name: community.crypto
  version: 2.20.0
- name: community.general
  version: 9.0.1
- name: fedora.linux_system_roles
  version: 1.78.2
- name: freeipa.ansible_freeipa
  version: 1.13.1
- name: microsoft.sql
  version: 2.2.3
- name: sap.linux
  version: 3.1.4
